
# 小程序组件
[Example]
Example= "用例示例"
[image]
image = "image 测试组件"
[File]
file = "file API的用例"
FileSystemManager = "FileSystemManager API的用例"
FileSystemManager2 = "FileSystemManager2 API的用例"
FileSystemManager3 = "FileSystemManager3 API的用例"
FileSystemManager4 = "FileSystemManager4 API的用例"
FileSystemManager5 = "FileSystemManager5 API的用例"
FileSystemManager6 = "FileSystemManager6 API的用例"
FileSystemManager7 = "FileSystemManager7 API的用例"
FileSystemManager8 = "FileSystemManager8 API的用例"
FileSystemManager9 = "FileSystemManager9 API的用例"
FileSystemManager10 = "FileSystemManager10 API的用例"
FileSystemManager11 = "FileSystemManager11 API的用例"
FileSystemManager12 = "FileSystemManager12 API的用例"
FileSystemManager13 = "FileSystemManager13 API的用例"
FileSystemManager14 = "FileSystemManager14 API的用例"
FileSystemManager15 = "FileSystemManager15 API的用例"
FileSystemManager16 = "FileSystemManager16 API的用例"
FileSystemManager17 = "FileSystemManager17 API的用例"
FileSystemManager18 = "FileSystemManager18 API的用例"
FileSystemManager19 = "FileSystemManager19 API的用例"
FileSystemManager20 = "FileSystemManager20 API的用例"